/**
* Lembrar: 
* 1 - id -> generated by default as identity primary pgsodium.key
* 2 - int_id -> bigint identity unique not null
	 Verifique se a coluna int_id ao ser criada ficou not null. Não pode haver valores nulos nesta coluna, se preciso use: 
 		ALTER TABLE superficial_sync ALTER COLUMN int_id SET NOT NULL;
* 3 - int_shape -> geometry SRID
	Adiciona srid na columna geometry
		ALTER TABLE superficial
  		ALTER COLUMN int_shape TYPE geometry(POINT, 4674)
    	USING ST_SetSRID(int_shape,4674);
*/

-- Atributos para criar a classe java. Esta query especifica: tabela, coluna e atributos:.
	select column_name, data_type, character_maximum_length, is_nullable, column_default
	from information_schema.columns
	where table_name = 'superficial'



    
    
    

 
 